global:
  scrape_interval: 15s # How often to scrape metrics (default is 15 seconds)

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Monitor itself (Prometheus)

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"] # Monitor Node Exporter

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9308"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"] # Add Redis Exporter if installed

  - job_name: "django"
    static_configs:
       - targets: ["web:8015"]


