# Generated by Django 5.1.4 on 2025-01-06 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bad6af00-4c41-482f-be84-d23c2be8dcac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
