# Generated by Django 5.1.4 on 2025-01-06 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34ae3d64-036a-4d5a-bdc8-42a932d80df6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
