# Generated by Django 5.1.4 on 2025-01-07 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64ff2502-eff6-4753-8d24-ccc7c1157466'), editable=False, primary_key=True, serialize=False),
        ),
    ]
