# Generated by Django 5.1.4 on 2025-01-07 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf121c8c-0e9e-4b35-a2c2-04f88577a0f8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
