# Generated by Django 5.1.4 on 2025-01-07 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d3011fdf-89ab-4bf0-89a3-73251f29d78b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
