# Generated by Django 5.1.4 on 2025-01-07 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84c1259f-21a1-4097-9df2-204ff5566a36'), editable=False, primary_key=True, serialize=False),
        ),
    ]
