# Generated by Django 5.1.4 on 2025-01-07 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b86e3a42-beba-4324-bfd7-aaa23b9f8a41'), editable=False, primary_key=True, serialize=False),
        ),
    ]
