# Generated by Django 5.1.4 on 2025-01-08 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36f579ad-f915-45a1-b909-a50e9dd49677'), editable=False, primary_key=True, serialize=False),
        ),
    ]
