# Generated by Django 5.1.4 on 2025-01-08 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0013_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c33f882-7d85-4a69-96f6-1f98559bbf44'), editable=False, primary_key=True, serialize=False),
        ),
    ]
