# Generated by Django 5.1.4 on 2025-01-08 13:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0669bad9-6c83-4b6f-a435-7ec1624e55e4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
