# Generated by Django 5.1.4 on 2025-01-08 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e21d3374-aca8-4fda-94f6-fc673a156bb6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
