# Generated by Django 5.1.4 on 2025-01-08 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0017_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('670d136a-bdbc-439b-aee5-1f85cebd8fa9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
