# Generated by Django 5.1.4 on 2025-01-08 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0018_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ae7d5c2-63b2-4152-ac5a-0971c7ef5155'), editable=False, primary_key=True, serialize=False),
        ),
    ]
