# Generated by Django 5.1.4 on 2025-01-08 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0019_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c25b4d2-893c-4f21-b842-b186de70769a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
