# Generated by Django 5.1.4 on 2025-01-08 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0020_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c5d31ac-1ba0-454f-8361-1bb79fc36124'), editable=False, primary_key=True, serialize=False),
        ),
    ]
