# Generated by Django 5.1.4 on 2025-01-13 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0022_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b3fa2aa-2a5c-41fc-870a-56c9daac5038'), editable=False, primary_key=True, serialize=False),
        ),
    ]
