# Generated by Django 5.1.4 on 2025-01-14 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0023_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0dce62fe-cd16-4055-8239-504c0cc4a4ac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
