# Generated by Django 5.1.4 on 2025-01-22 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0024_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74d93baa-e406-43ea-b63d-4ac41e1bc188'), editable=False, primary_key=True, serialize=False),
        ),
    ]
