# Generated by Django 5.1.4 on 2025-01-22 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0025_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520b75-6af9-4b06-a35e-8499c352ca7d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
