# Generated by Django 5.1.4 on 2025-01-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview image for the course.', null=True, upload_to='uploads/course_previews'),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video',
            field=models.FileField(blank=True, help_text='Introductory video for the course.', null=True, upload_to='uploads/course_videos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Data Science', 'Data Science'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Business', 'Business')], max_length=100),
        ),
    ]
