# Generated by Django 5.1.4 on 2025-01-22 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_price_courseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('70585ad8-7ff0-48a2-8b86-04d3cf55c5d4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
